package com.hand.address.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.MultiLanguage;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
//多语言表字段
@MultiLanguage
@ExtensionAttribute(disable=true)
@Table(name = "address_list")
public class addressList extends BaseDTO {
    @Id
    @GeneratedValue
    @Column
    private Long id;
    @Column
    @MultiLanguageField
    private String name;
    @Column
    private String sex;
    @Column
    private String phone;
    @Column
    private String email;
    @Column
    @MultiLanguageField
    private String address;


    public void setId(Long id){
        this.id = id;
    }

    public Long getId(){
        return id;
    }

    public void setName(String name){
        this.name = name;
    }

    public String getName(){
        return name;
    }

    public void setSex(String sex){
        this.sex = sex;
    }

    public String getSex(){
        return sex;
    }

    public void setPhone(String phone){
        this.phone = phone;
    }

    public String getPhone(){
        return phone;
    }

    public void setEmail(String email){
        this.email = email;
    }

    public String getEmail(){
        return email;
    }

    public void setAddress(String address){
        this.address = address;
    }

    public String getAddress(){
        return address;
    }

}
